version: '3.2'

services:
  zeek:
    image: ethack/zeek
    build: .

    cap_add:
      - net_raw
    network_mode: host

    volumes:
      - type: bind
        source: ./logs
        target: /usr/local/zeek/logs

      - type: bind
        source: ./etc/networks.cfg
        target: /usr/local/zeek/etc/networks.cfg

      - type: bind
        source: ./etc/node.cfg
        target: /usr/local/zeek/etc/node.cfg

      - type: bind
        source: ./etc/zeekctl.cfg
        target: /usr/local/zeek/etc/zeekctl.cfg

      - type: bind
        source: ./share/zeek/site/local.zeek
        target: /usr/local/zeek/share/zeek/site/local.zeek

