name: Publish Docker Image to Github Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish the docker image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ethack
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: zeek
